### PR TITLE
Add function to reset all timers at once

### PR DESCRIPTION
**Pull request by bizprof**
Very much like this library, for its combination of usefulness and simplicity!

For a project of mine (Nixie clock with periodic updates over NTP and RTC), I was looking for an easy option to reset all timers at once, without having to reset every single one individually. 

Hence this pull request. Hope it doesn't add too much complexity to the library. 
Basically, it is introducing a simple list of BlockNot instances, which gets populated whenever a new timer is instantiated. The <code>resetAllTimers()</code> function then calls <code>reset()</code> for all instances. 

Have also added an example of how to use <code>resetAllTimers()</code>.
Would be great if you could add this to your library! 

Cheers, Michael

### CODE REVIEW

**Comment by EasyG0ing1** [comment]
Hi Michael!

Thank you for contributing to the project. I'll have a look at this and see how it all works. If I had any concerns at all, it would be with any additional CPU time being consumed under "normal" usage of the library. This library started as something very simple, then as I was using it, I added all kinds of features to it, only to learn that I was adding too much overhead to the library and in one of my projects, the extra features ended up slowing things down to the point where the library was not useful for its original purpose, so I scrapped it and started over and this is what I ended up with. But as long as the new code doesn't add any significant overhead, I'd be happy to include it in the library... stay tuned ... :-)

**Comment by EasyG0ing1** [comment]
@bizprof Michael,

So I created a new library and called it BlockNotPull and I used your version of the library, and right away, when I ran a test compile for a Nano, I immediately got back from the compiler that it could not find forward_list.

So I tried it with the NEW IDE (the one that's in Beta right now) and I got the same error message.

Is forward_list possibly unique to specific boards and that's why it's not being found by a default install of the Arduino IDE set up for a Nano?

**Comment by EasyG0ing1** [comment]
@bizprof Michael,

OK, I did some poking around and I found forward_list under the ESP32 hardware folder so I changed my board to an ESP32 type and it compiled just fine.

But for obvious reasons, I can't have the library only work for one board type. It needs to compile for any Arduino-compatible processor.

If you can somehow make the new feature work so that it compiles for any board, I'll check it out again and if everything looks good, I'll merge it.

**Comment by bizprof** [comment]
Hi Michael,

Thanks for looking into my PR. I will have to check why it didn't compile for you. 
I had tested it with Arduino 1.8.15, installed as a Windows app, version 1.8.40.0.
Tried two boards (NANO 33 IoT and a no-name ESP32 Dev Module), and it worked for both.

forward_list is a an old C and C++ function, quite surprised about it not being found. 
Will check where it comes from for different boards, and get back to you.

Thanks again for checking it out!

Michael

**Comment by EasyG0ing1** [comment]
@bizprof Michael,

I could not find a Nano 33 IoT in my list of boards, HOWEVER, I did see a Nano32 under the ESP32 flavor of boards. I suspect that the Nano33 IoT would most likely also be classified as an ESP32 board.

Try selecting a standard Nano under standard AVR boards in your IDE and then do a test compile ... I think you'll see the same error that I am seeing.

Mike

**Comment by bizprof** [comment]
Will do, thanks Mike. The NANO 33 IoT is actually an official Arduino product, based on the SAMD21 architecture, but it's not included in the standard IDE. Anyway, I'll check how it is implemented for different boards and get back to you. Totally agree, you can't have a library that only works for some boards!

**Comment by bizprof** [comment]
Hi Mike, sorry I didn't check this out with more boards. It turns out that the standard Arduino IDE does not come with any support for the C++ Standard Template Library (STL). This library would have included the forward_list implementation. 
Reason given is usually that there are some resource-hungry classes that don't work with the smaller boards.
So, most modern (and more powerful) boards bring along their own STL implementation. It gets installed when you install support for those boards with the Boards Manager in the Arduino IDE. That's why it worked without problems for the Arduino NANO 33 IoT, ESP8266 and ESP32. 
Installing the whole STL for every board under the sun, for just a forward_list implementation, is overkill, though, and would open a whole new can of worms. GitHub has plenty of abandoned STLs for Arduino. 
Will look into coding the needed functionality myself, rather than using forward_list. Only a small subset is needed anyway.
Who would have thought that such a simple standard function is not supported by the IDE.
Will let you know when I have something that works across all bords.
Cheers, Michael

**Comment by EasyG0ing1** [comment]
@bizprof Michael,

I had an idea that might work out if you're willing to do a little extraction mission ...

If you were to extract from the Standard Template Library, only the code the creates and supports forward_list, we could create a separate library for that function only and just manually add it to BlockNot so that it's always there no matter which platform is being used. 

Of course, I would make sure it compiles on all platforms that are default to the IDE but provided that works, it would be a fairly simple workaround to get the feature implemented without re-inventing the wheel - so to speak.

Prior to you creating this pull request, I was not familiar with the Standard Template Library nor with forward_list, but I like the way it works with BlockNot giving users the ability to address all of their timers in a single array or address them individually as they prefer. It's a powerful function requiring very minimal changes to the core library (which is always a bonus).

Let me know what you think of the idea.

Mike

**Comment by bizprof** [comment]
Hi Mike,

That's a great idea indeed. I found a STL package that had <code>forward_list</code> in it (not all of them do, as it is not very commonly used) and tried to make it work. Had to give up for multiple reasons:

- The STL source files are deeply entangled via #includes - whenever I thought I had extracted all that was needed, another missing file would pop up. Decided to include the whole STL package, see whether it works, and then delete the files that weren't needed instead.

- The STL package turned out to still be platform-dependent. I got compiler errors at a deeply atomic level, basically where the C++ standard data types are being mapped to the hardware capabilities. There is no STL package (or at least, I could not find one) that would address those compatibility issues across all the boards supported by the IDE

In the end, I decided to write the timer list from scratch directly into the BlockNot class, without the need for any 3rd party code. Will update my PR soon. 

Have tested my ResetAll example sketch on ESP32, ESP8266, Arduino Uno, Arduino NANO 33 IoT, and even the latest NANO RP2040 Connect. Works as it should. 

Cheers, Michael

**Comment by bizprof** [comment]
Hi Mike,
I've updated my PR to incorporate your changes for the SECOND timers (and updated my example sketch accordingly). Please take a look and see whether it works for you. 
Time to call it a day over here in the UK now...
Cheers, Michael

**Review by EasyG0ing1 — APPROVED** [review]

**Comment by EasyG0ing1** [comment]
@bizprof Michael,

Could you open a new pull request with the code that you got working and the example that you got working? With all of the changes that were going on, I had a difficult time sifting through it all, but a new PR would be clean and easy. I definitely want to make this work.

**Comment by bizprof** [comment]
Looks like the new PR (#5) still has all the commits as separate items. Will probably have to restart afresh with a new fork. Not too familiar how I could merge the commits into one on GitHub...

**Pull request closed without merging**
